name: Website Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  test-approval:
    environment: uat
    runs-on: ubuntu-latest
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          debug: true
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"